# Use the official Jupyter SciPy Notebook as a base image
FROM jupyter/minimal-notebook:latest

WORKDIR /home/jovyan/work
COPY requirements-graph.txt /home/jovyan/work/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
# Copy the log file and notebook into the container's work directory
# Expose port 8888 (the default Jupyter Notebook port)
EXPOSE 8888

# Start the Jupyter Notebook server when the container launches
CMD ["start-notebook.sh"]
